const {_electron:electron}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {createCompanion}=require('../src/core/companion.cjs'),{localDay}=require('../src/core/moments.cjs');
const root=path.join(__dirname,'..'),out=path.join(root,'test-results'),profile=path.join(out,`moments-${Date.now()}`);
const env={...process.env,BANBAN_TEST:'1',BANBAN_TEST_DATA:profile};delete env.ELECTRON_RUN_AS_NODE;delete env.BANBAN_TEST_SENSOR;delete env.BANBAN_GIFT_MANIFEST;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));let app,settings,pet;const report={date:new Date().toISOString(),checks:[]},errors=[];
async function until(fn){for(let i=0;i<160;i++){if(await fn())return;await sleep(50);}throw Error('Timed out');}
const call=(name,...args)=>settings.evaluate(({name,args})=>window.banban.call(name,...args),{name,args});
const runtime=()=>JSON.parse(fs.readFileSync(path.join(profile,'runtime.json'),'utf8'));
async function moment(){let page;await until(()=>Boolean(page=app.windows().find(p=>p.url().endsWith('moment.html'))));await page.waitForSelector('#title:not(:empty)');await until(async()=>(await call('test-control',{action:'metrics'})).moment?.visible);return page;}
async function close(page){await page.locator('#close').click({force:true});await until(()=>page.isClosed());}
(async()=>{try{
 const launch={env,args:[root,'--settings']};if(process.argv.includes('--packaged')){launch.executablePath=path.join(root,'release','win-unpacked','伴伴.exe');launch.args=['--settings'];}
 app=await electron.launch(launch);app.on('window',p=>p.on('pageerror',e=>errors.push(e.message)));await until(()=>Boolean(settings=app.windows().find(p=>p.url().endsWith('settings.html'))));await settings.waitForSelector('[data-action="start"]');
 await call('save-settings',{nickname:'小朋友',sender:'大朋友',petCharacter:'dog'});await call('start');pet=app.windows().find(p=>p.url().endsWith('pet.html'));await pet.waitForSelector('svg');await sleep(350);
 await settings.locator('nav [data-page="moments"]').click();await settings.locator('#anniversary-date').fill('2024-02-20');await settings.locator('#anniversary-title').fill('在一起的日子');
 const letter='{昵称}：\n\n'+('每一个平凡的日子，都因为你变得值得收藏。\n'.repeat(42))+'\n一直喜欢你的{我的称呼}';await settings.locator('#anniversary-letter').fill(letter);
 await settings.locator('[data-setting="moments.anniversary.enabled"]').check();await until(async()=>(await call('get-state')).config.moments.anniversary.enabled);
 assert.equal(await settings.locator('[data-action="preview-moment"]').count(),3);assert.equal(await settings.locator('[data-value="gacha"],#compliments,#coupons').count(),0);assert.equal((await settings.locator('body').innerText()).includes('夸夸扭蛋'),false);
 const authorLabels=await call('test-control',{action:'menu-labels'});assert.ok(authorLabels.includes('抱抱我'));assert.ok(!authorLabels.some(x=>x.includes('扭蛋')));await assert.rejects(()=>call('open-moment','gacha'),/没有这个小惊喜/);await assert.rejects(()=>call('preview-moment','gacha'),/没有这个小惊喜/);
 report.checks.push('Creator has three surprise settings and no capsule menu, editor or callable surprise');
 await settings.screenshot({path:path.join(out,'v1.4.1-moments-settings.png')});
 await settings.locator('[data-action="preview-moment"][data-value="anniversary"]').click();let card=await moment();assert.equal(await card.locator('#overline').innerText(),'在一起的日子');await sleep(900);await card.screenshot({path:path.join(out,'v1.4-bouquet.png')});
 await card.locator('#actions button').first().click();await card.waitForSelector('.reading');await sleep(100);
 const joined=await card.evaluate(()=>{const result=[];do{result.push(document.querySelector('#letter-text').textContent);const next=document.querySelector('#next');if(next.disabled)break;next.click();}while(result.length<100);return result.join('');});assert.equal(joined,letter.replaceAll('{昵称}','小朋友').replaceAll('{我的称呼}','大朋友'));
 const overflow=await card.locator('#letter-text').evaluate(el=>el.scrollHeight>el.clientHeight+1);assert.equal(overflow,false);await card.locator('#previous').click();await card.screenshot({path:path.join(out,'v1.4-letter.png')});await close(card);
 report.checks.push('Creator saves anniversary date, name and long letter; bouquet opens paginated complete text without scrolling');
 // Hold uses the real pointer handlers and fallback drag loop, not a direct moment call.
 await pet.locator('.cat-head').hover({force:true});await pet.mouse.down();await sleep(1500);assert.equal((await call('test-control',{action:'metrics'})).moment,null);await sleep(650);card=await moment();assert.ok((await card.locator('#message').innerText()).includes('小朋友'));await pet.mouse.up();await card.screenshot({path:path.join(out,'v1.4-hug.png')});await close(card);
 await pet.mouse.down();await call('test-control',{action:'finish-test-drag'});await pet.mouse.up();await sleep(2100);assert.equal((await call('test-control',{action:'metrics'})).moment,null);report.checks.push('Holding two seconds triggers hug; dragging cancels it and release does not add a tap');
 await call('open-moment','umbrella');card=await moment();await card.screenshot({path:path.join(out,'v1.4-umbrella.png')});await card.locator('#actions button').last().click();await until(()=>card.isClosed());assert.equal((await call('get-state')).status.reason,'提醒已暂停');await call('pause','resume');report.checks.push('Umbrella offers comfort and its quiet option pauses automatic reminders for thirty minutes');
 let c=(await call('get-state')).config;c.moments.anniversary.date=localDay();await call('save-settings',{moments:c.moments});await pet.locator('.cat-head').click({force:true});card=await moment();assert.equal((await call('test-control',{action:'metrics'})).moment.kind,'anniversary');assert.equal(runtime().anniversarySeen.length,1);await close(card);await pet.locator('.cat-head').click({force:true});assert.equal((await call('test-control',{action:'metrics'})).moment,null);
 await app.close();app=await electron.launch(launch);await until(()=>Boolean(settings=app.windows().find(p=>p.url().endsWith('settings.html'))));await settings.waitForSelector('h1');pet=app.windows().find(p=>p.url().endsWith('pet.html'));await pet.waitForSelector('svg');await pet.locator('.cat-head').click({force:true});assert.equal((await call('test-control',{action:'metrics'})).moment,null);assert.equal(runtime().anniversarySeen.length,1);report.checks.push('Anniversary first touch triggers exactly once per day, including after restart');
 c=(await call('get-state')).config;await app.close();app=null;const manifest=path.join(out,`moments-recipient-${Date.now()}.json`);fs.writeFileSync(manifest,JSON.stringify(createCompanion(c)));
 app=await electron.launch({...launch,env:{...env,BANBAN_TEST_DATA:profile+'-recipient',BANBAN_GIFT_MANIFEST:manifest}});await until(()=>Boolean(pet=app.windows().find(p=>p.url().endsWith('pet.html'))));await pet.waitForSelector('svg');assert.equal(app.windows().some(p=>p.url().endsWith('settings.html')),false);
 const rc=(name,...args)=>pet.evaluate(({name,args})=>window.banban.call(name,...args),{name,args});const labels=await rc('test-control',{action:'menu-labels'});assert.ok(!labels.some(x=>x.includes('扭蛋')));assert.ok(labels.includes('抱抱我'));await assert.rejects(()=>rc('open-moment','gacha'),/没有这个小惊喜/);assert.ok(labels.some(x=>x.includes('情绪小伞')));await assert.rejects(()=>rc('preview-moment','hug'));await assert.rejects(()=>rc('save-settings',{moments:c.moments}));
 await rc('open-moment','anniversary');let received;await until(()=>Boolean(received=app.windows().find(p=>p.url().endsWith('moment.html'))));await received.waitForSelector('#title:not(:empty)');assert.equal(await received.locator('#overline').innerText(),'在一起的日子');await received.locator('#close').click({force:true});report.checks.push('Recipient receives all authored moments and menu actions, with no creator settings or preview access');
 assert.deepEqual(errors,[]);report.passed=true;console.log(JSON.stringify(report,null,2));
}catch(error){report.passed=false;report.failure=error.stack;console.error(error);process.exitCode=1;}finally{if(app)await app.close().catch(()=>{});report.errors=errors;fs.writeFileSync(path.join(out,'moments-report.json'),JSON.stringify(report,null,2));}})();
